name: practice
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: wishing
        run: echo "Hi all"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: send off
        run: echo "By all"
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
      - name : completed all jobs
        run: echo "All jobs execution completed"
